language: php
php:
  - 7.2

sudo: required

services:
  - docker

addons:
  hosts:
    - fedora

install:
  - cp config.ini.sample config.ini
  - sed 's|sparqlUrl=".*"|sparqlUrl="http://fedora/blazegraph/sparql"|' config.ini.sample > tests/config.ini
  - composer update
  # initialize the database and allow apache-php inside docker access to it 
  # (as sqlite creates temp files in the db file dir it requires file creation rights on the dir)
  - php -f cleanup.php && chmod 666 db.sqlite && chmod 777 .
  # allow apache-php inside docker to write to the log file
  - touch log && chmod 666 log
  # build & run docker containers
  - docker build -t acdh/fedora tests/docker/fedora
  - docker build -t acdh/blazegraph tests/docker/blazegraph
  - docker build -t acdh/karaf tests/docker/karaf
  - docker build -t acdh/www tests/docker/www
  - docker network create -d bridge repo
  - docker run -d --name=fedora --network=repo acdh/fedora
  - docker run -d --name=blazegraph --network=repo acdh/blazegraph
  - docker run -d --name=www --network=repo -p 80:80 -v `pwd`:/var/www/html acdh/www
  - docker run -d --name=karaf --network=repo acdh/karaf
  # give containers time to start
  - sleep 5
  # initialize repo
  - php -f tests/init.php
  # download & import ontology - required by some tests
  - git clone https://github.com/acdh-oeaw/repo-schema && ln -s ../vendor repo-schema/vendor && ln -s ../tests/config.ini repo-schema/config.ini
  - php -f repo-schema/importOntology.php repo-schema/acdh-schema.owl skipBinary

script:
  - php -f tests/_runAll.php
