metadataManagment:
    nonRelationProperties:
        - http://www.w3.org/1999/02/22-rdf-syntax-ns#type
        - http://www.w3.org/2000/01/rdf-schema#range
        - http://www.w3.org/2000/01/rdf-schema#domain
        - http://www.w3.org/2002/07/owl#onProperty
        - http://www.w3.org/2002/07/owl#onDataRange
        - http://www.w3.org/2002/07/owl#onClass
rest:
    handlers:
        methods:
            create:
                - type: function
                  function: \acdhOeaw\arche\Doorkeeper::onResEdit
            updateBinary:
                - type: function
                  function: \acdhOeaw\arche\Doorkeeper::onResEdit
            updateMetadata:
                - type: function
                  function: \acdhOeaw\arche\Doorkeeper::onResEdit
            txCommit:
                - type: function
                  function: \acdhOeaw\arche\Doorkeeper::onTxCommit
schema:
    creationDate: 'https://vocabs.acdh.oeaw.ac.at/schema#hasAvailableDate'
    mime: 'https://vocabs.acdh.oeaw.ac.at/schema#hasFormat'
    acdh:
        binarySize: 'https://vocabs.acdh.oeaw.ac.at/schema#hasBinarySize'
        pid: 'https://vocabs.acdh.oeaw.ac.at/schema#hasPid'
        hosting: 'https://vocabs.acdh.oeaw.ac.at/schema#hasHosting'
        accessRestriction: 'https://vocabs.acdh.oeaw.ac.at/schema#hasAccessRestriction'
        accessRole: 'https://vocabs.acdh.oeaw.ac.at/schema#hasRestrictionRole'
        count: 'https://vocabs.acdh.oeaw.ac.at/schema#hasNumberOfItems'
    classes:
        repoObject: 'https://vocabs.acdh.oeaw.ac.at/schema#RepoObject'
        sharedObject: 'https://vocabs.acdh.oeaw.ac.at/schema#AgentOrPlaceOrPublication'
        container: 'https://vocabs.acdh.oeaw.ac.at/schema#Container'
    namespaces:
        ontology: 'https://vocabs.acdh.oeaw.ac.at/schema#'
doorkeeper:
    default:
        hosting: 'https://id.acdh.oeaw.ac.at/arche'
        accessRestriction: 'https://vocabs.acdh.oeaw.ac.at/archeaccessrestrictions/public'
    rolePublic: public
    roleAcademic: academic
    uriMappings:
        '|^https?://([^.]*[.])?geonames[.]org/([0-9]+)(/.*)?$|': 'https://www.geonames.org/\2'
        '|^https?://([^.]*[.])?gazetteer[.]dainst[.]org/([A-Za-z]+/)*([0-9]+)([^0-9].*)?$|': 'https://gazetteer.dainst.org/place/\3'
        '|^https?://([^.]*[.])?pleiades[.]stoa[.]org/places/([0-9]+)(/.*)?$|': 'https://www.pleiades.stoa.org/places/\2'
        '|^https?://([^.]*[.])?viaf[.]org/viaf/([0-9]+)(/.*)?$|': 'https://viaf.org/viaf/\2'
        '|^https?://([^.]*[.])?d-nb[.]info/gnd/([0-9]+-[0-9]+)$|': 'https://d-nb.info/gnd/\2'
        '|^https?://([^.]*[.])?wikidata[.]org/([A-Za-z:]+/)*(Q[0-9]+)([^[0-9].*)?$|': 'https://www.wikidata.org/entity/\3'
        '|^https?://([^.]*[.])?orcid[.]org/([0-9]{4})-?([0-9]{4})-?([0-9]{4})-?([0-9]{4})$|': 'https://orcid.org/\2-\3-\4-\5'
        '|^https?://([^.]*[.])?n2t[.]net/ark:/99152/(p0[a-z0-9]+)$|': 'https://n2t.net/ark:/99152/\2'
        '|^https?://([^.]*[.])?chronontology[.]dainst[.]org/period/([A-Za-z0-9]+)$|': 'https://chronontology.dainst.org/period/\2'
    epicPid:
        resolver: 'http://hdl.handle.net/'
        url: 'https://pid.gwdg.de/handles/'
        user: user21.11115-01
        pswd: 
        prefix: 21.11115
    # used only by tests
    restConfigSrcPath: /home/zozlak/roboty/ACDH/repo/rdbms/tests/config.yaml
    # used only by tests
    restConfigDstPath: /home/zozlak/roboty/ACDH/repo/rdbms/config.yaml
        