metadataManagment:
    nonRelationProperties:
        - http://www.w3.org/1999/02/22-rdf-syntax-ns#type
        - https://vocabs.acdh.oeaw.ac.at/schema#hasPid
        - https://vocabs.acdh.oeaw.ac.at/schema#matchesProp
rest:
    handlers:
        methods:
            create:
                - type: function
                  function: \acdhOeaw\arche\doorkeeper\Resource::onResEdit
            updateBinary:
                - type: function
                  function: \acdhOeaw\arche\doorkeeper\Resource::onResEdit
            updateMetadata:
                - type: function
                  function: \acdhOeaw\arche\doorkeeper\Resource::onResEdit
            txCommit:
                - type: function
                  function: \acdhOeaw\arche\doorkeeper\Transaction::onTxCommit
schema:
    id: https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
    label: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
    creationDate: https://vocabs.acdh.oeaw.ac.at/schema#hasAvailableDate
    mime: https://vocabs.acdh.oeaw.ac.at/schema#hasFormat
    binarySizeCumulative: https://vocabs.acdh.oeaw.ac.at/schema#hasBinarySize
    pid: https://vocabs.acdh.oeaw.ac.at/schema#hasPid
    hosting: https://vocabs.acdh.oeaw.ac.at/schema#hasHosting
    isNewVersionOf: https://vocabs.acdh.oeaw.ac.at/schema#isNewVersionOf
    accessRestriction: https://vocabs.acdh.oeaw.ac.at/schema#hasAccessRestriction
    accessRole: https://vocabs.acdh.oeaw.ac.at/schema#hasRestrictionRole
    countCumulative: https://vocabs.acdh.oeaw.ac.at/schema#hasNumberOfItems
    oaipmhSet: https://vocabs.acdh.oeaw.ac.at/schema#hasOaiSet
    classes:
        repoObject: https://vocabs.acdh.oeaw.ac.at/schema#RepoObject
        sharedObject: https://vocabs.acdh.oeaw.ac.at/schema#AgentOrPlaceOrPublication
        container: https://vocabs.acdh.oeaw.ac.at/schema#Container
        topCollection: https://vocabs.acdh.oeaw.ac.at/schema#TopCollection
        collection: https://vocabs.acdh.oeaw.ac.at/schema#collection
    namespaces:
        ontology: https://vocabs.acdh.oeaw.ac.at/schema#
    ontology:
        order: https://vocabs.acdh.oeaw.ac.at/schema#ordering
        recommended: https://vocabs.acdh.oeaw.ac.at/schema#recommendedClass
        langTag: https://vocabs.acdh.oeaw.ac.at/schema#langTag
        vocabs: https://vocabs.acdh.oeaw.ac.at/schema#vocabs
doorkeeper:
    rolePublic: public
    roleAcademic: academic
    checkRanges:
        https://vocabs.acdh.oeaw.ac.at/schema#Agent: [viaf, orcid, gnd, wikidata, arche-localhost, acdhi, arche, pmb]
    # Should Doorkeeper::checkUnknownProperties() be run? We need to be able to turn it off for the ontology import.
    checkUnknownProperties: true
    # Should Doorkeeper::checkAutoCreatedResources() be run? We need to be able to turn it off for the ontology import.
    checkAutoCreatedResources: true
    # Should Doorkeeper::maintainPropertyRangeVocabs() be run? We need to be able to turn it off for the ontology import.
    checkVocabularyValues: true
    epicPid:
        resolver: https://hdl.handle.net/
        url: http://test/handles/
        user: user21.11115-01
        pswd: foobar
        prefix: 21.11115
        createValue: create
        clarinSet: https://vocabs.acdh.oeaw.ac.at/archeoaisets/clarin-vlo
        clarinSetProperty: https://vocabs.acdh.oeaw.ac.at/schema#hasOaiSet
    # used only by tests
    restConfigDstPath: config/yaml/config-repo.yaml
        
