name: phpunit

on: push

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: clone repo config
      run: |
        git clone --depth 1 --branch rdfInterface https://github.com/acdh-oeaw/arche-docker-config.git config
        chmod +x config/run.d/xdebug.sh
        rm -f config/run.d/gui.sh config/run.d/oaipmh.sh config/run.d/resolver.sh config/run.d/fcs.sh config/run.d/openrefine.sh config/run.d/refsources.sh config/initScripts/30-dissServices.php
        cp .github/workflows/test-postgresql_config.sh config/run.d/
        cp .github/workflows/*-testSetup.sh config/initScripts/
        cp config-sample.yaml config/yaml/doorkeeper.yaml
        sed -e 's/pswd:/pswd: foobar/g' config/yaml/local.yaml.sample > config/yaml/local.yaml
        sed -ie 's/"acdh-oeaw\/arche-doorkeeper".*/"acdh-oeaw\/arche-doorkeeper": "dev-rdfInterface",/g' config/composer.json
    - name: run repo docker
      run: |
        mkdir -p build/logs log
        docker run --name arche -p 80:80 -p 5432:5432 -v `pwd`/build:/home/www-data/docroot/api/build -v `pwd`/log:/home/www-data/log -v `pwd`/config:/home/www-data/config -v `pwd`:/home/www-data/arche-doorkeeper -e USER_UID=`id -u` -e USER_GID=`id -g` -d acdhch/arche
    - name: composer update
      run: |
        composer update
    - name: wait
      run: |
        while [ "`grep '# INIT SCRIPTS ENDED' log/initScripts.log | wc -l`" != "1" ]; do
          tail log/initScripts.log || true
          echo "Waiting until repository is ready..."
          echo "-----"
          sleep 10
        done
        cat log/initScripts.log
    - name: test
      run: |
        XDEBUG_MODE=coverage ./vendor/bin/phpunit
    - name: coveralls
      run: |
        export COVERALLS_RUN_LOCALLY=1
        export COVERALLS_REPO_TOKEN=${{ secrets.coverallsToken }}
        composer require -W php-coveralls/php-coveralls
        php vendor/bin/php-coveralls -v
        head -n 10 build/logs/clover.xml
    - name: debug
      if: ${{ failure() }}
      run: |
        cat log/rest.log
